site_name: My Docs
theme:
  name: material
  features:
    - navigation.instant
  palette:
    scheme: default
  icon:
    repo: fontawesome/brands/github
    
repo_url: https://github.com/jratke587/wiki/
repo_name: Edit on Github
